Fix build on Mono
Add ICSharpCode.NRefactory.dll and reference it to fix Mono build
error:

MonoDevelop.Paket/PaketSyntaxModes.cs(43,15): error CS0012: The type
`ICSharpCode.NRefactory.Editor.IDocument' is defined in an assembly
that is not referenced. Consider adding a reference to assembly
`ICSharpCode.NRefactory, Version=5.0.0.0, Culture=neutral, PublicKeyToken=d4bfe873e7598c49'